public enum ASTNodeType {
    // не токен-узлы (не листья)
    PHRASEFUNCTIONDEFINITION,
    PHRASEMAINFUNCTIONDEFINITION,
    PHRASEFOR,
    PHRASEIF,
    PHRASEELSE,
    PHRASEWHILE,

    EXPRESSIONVARIABLEDEFINITION,
    EXPRESSIONASSIGNMENT,
    EXPRESSIONASSERTMACRO,
    EXPRESSIONPRINTLNMACRO,
    EXPRESSIONRETURN,

    SENTENCEFUNCTIONDEFINITIONPARAM,
    SENTENCEFUNCTIONPARAM,
    SENTENCEASSERTPARAM,
    SENTENCEPRINTLNPARAM,
    SENTENCEINDEX,
    SENTENCEE,

    CONDITIONFOR,
    CONDITIONIF,
    CONDITIONWHILE,

    ARRAYDECLARATION,
    ARRAYINDEX,
    ARRAYELEMENT,

    FUNCTIONDECLARATION,
    MAINDECLARATION,
    TYPEBINDING,
    BINDING,
    MUTABLEDEFINITION,
    CYCLE,
    POINTFUNCTION,

    PROGRAM,
    BODY,

    // токен-узлы (листья)
    ID,
    FUNCTIONID,
    COMMA,
    SEMICOLON,
    QUOTES,
    // круглые скобки
    LPARENTHESIS,
    RPARENTHESIS,
    // фигурные скобки
    LBRACE,
    RBRACE,
    // квадратные скобки
    LSQUAREBRACKET,
    RSQUAREBRACKET,
    // операции
    OPERATOREQUALITY,
    OPERATORINEQUALITY,
    OPERATORASSIGNMENT,
    OPERATORSUMMING,
    OPERATORDIFFERENCE,
    OPERATORMULTIPLICATION,
    OPERATORDIVISION,
    OPERATORMODULO,
    OPERATORAND,
    OPERATOROR,
    OPERATORNOT,
    OPERATORLESS,
    OPERATORMORE,
    // типы данных
    INT,
    FLOAT,
    ARRAY,
    STRING,
    // значения переменных
    INTVARIABLE,
    SINTVARIABLE,
    FLOATVARIABLE,
    STRINGVARIABLE,
    HEXVARIABLE,
    OCTALVARIABLE,
    BINARYVARIABLE,
    CHAR,
    // операторы
    IN,
    ROUND,
    POINT,
    IF,
    ELSE,
    FOR,
    WHILE,
    // определение
    MUTABLE,
    COLON,
    FUNCTIONDEFINITION,
    VARIABLEDEFINITION,
    //
    MAIN,
    RETURN,
    FUNCTIONRETURN,
    // макросы
    ASSERTMACRO,
    PRINTLNMACRO,
    // узлы описание типов идентификаторов
    DESCRIPTIONINT,
    DESCRIPTIONFLOAT,
    DESCRIPTIONSTRING
}
