public enum ASTNodeType {
    // не токен-узлы (не листья)
    PHRASEFUNCTIONDEFINITION,
    PHRASEFOR,
    PHRASEIF,
    PHRASEELSE,
    PHRASEWHILE,

    EXPRESSIONVARIABLEDEFINITION,
    EXPRESSIONASSIGNMENT,
    EXPRESSIONASSERTMACRO,
    EXPRESSIONPRINTLNMACRO,
    EXPRESSIONRETURN,

    SENTENCEFUNCTIONDEFINITIONPARAM,
    SENTENCEFUNCTIONPARAM,
    SENTENCEASSERTPARAM,
    SENTENCEPRINTLNPARAM,
    SENTENCEE,

    CONDITIONFOR,
    CONDITIONIF,
    CONDITIONWHILE,

    FUNCTIONDECLARATION,
    MAINDECLARATION,
    TYPEBINDING,
    BINDING,
    MUTABLEDEFINITION,
    CYCLE,

    PROGRAM,
    MAINFUNCTIONEXPRESSION,
    FUNCTIONEXPRESSION,
    BODY,
    BODYEXPRESSION,
    DEFINITIONVARIABLEEXPRESSION,
    MUTABLEEXPRESSION,
    FOREXPRESSION,
    INEXPRESSION,
    IFEXPRESSION,
    ELSEEXPRESSION,
    WHILEEXPRESSION,
    ASSERTMACROEXPRESSION,
    PRINTLNMACROEXPRESSION,

    // токен-узлы (листья)
    ID,
    FUNCTIONID,
    COMMA,
    SEMICOLON,
    QUOTES,
    // круглые скобки
    LPARENTHESIS,
    RPARENTHESIS,
    // фигурные скобки
    LBRACE,
    RBRACE,
    // квадратные скобки
    LSQUAREBRACKET,
    RSQUAREBRACKET,
    // операции
    OPERATOREQUALITY,
    OPERATORINEQUALITY,
    OPERATORASSIGNMENT,
    OPERATORSUMMING,
    OPERATORDIFFERENCE,
    OPERATORMULTIPLICATION,
    OPERATORDIVISION,
    OPERATORMODULO,
    OPERATORAND,
    OPERATOROR,
    OPERATORNOT,
    OPERATORLESS,
    OPERATORMORE,
    // типы данных
    INT,
    FLOAT,
    ARRAY,
    STRING,
    // значения переменных
    INTVARIABLE,
    SINTVARIABLE,
    FLOATVARIABLE,
    STRINGVARIABLE,
    HEXVARIABLE,
    OCTALVARIABLE,
    BINARYVARIABLE,
    // операторы
    IN,
    ROUND,
    IF,
    ELSE,
    FOR,
    WHILE,
    // определение
    MUTABLE,
    COLON,
    FUNCTIONDEFINITION,
    VARIABLEDEFINITION,
    //
    MAIN,
    RETURN,
    FUNCTIONRETURN,
    // макросы
    ASSERTMACRO,
    PRINTLNMACRO
}
